name: TelewireAnalytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - pandas=1.3.3
  - matplotlib=3.4.3
  - scikit-learn=1.0
  - seaborn=0.11.2
  - joblib==1.2.0
  - numpy==1.24.2
  - plotly==5.14.0
  - scikit-learn==1.0.2
  - streamlit==1.20.0
  - altair==4.2.2
  - dill==0.3.6

